### ISSUE TITLE
comments in style can not be use on props

### ISSUE THREAD

**Issue by syf20020816** [palpus-rs/Gen-UI#1]
```css
// this is ok (现在只能在上面写)
.ui{
  // this is height ❌(issue,这里应该允许这样写)
  height: 160;
}
```
